# Generated by Django 3.1.12 on 2025-01-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20250126_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
